default: &default
  adapter: mysql2
  username: root
  password: 123
  host: 127.0.0.1 

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_quiz

test:
  <<: *default
  database: rails_quiz_test

production:
  <<: *default
  database: rails_quiz_production