default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQLDB_USER'] %>
  password: <%= ENV['MYSQLDB_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQLDB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['MYSQLDB_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['MYSQLDB_TEST_DATABASE'] %>
  username: <%= ENV['MYSQLDB_TEST_USER'] %>
  password: <%= ENV['MYSQLDB_ROOT_TEST_PASSWORD'] %>
  host: <%= ENV['MYSQLDB_TEST_HOST'] %>


production:
  <<: *default
  adapter: mysql2
  database: <%= ENV['MYSQLDB_DATABASE'] %>
  username: <%= ENV['MYSQLDB_USER'] %>
  password: <%= ENV['MYSQLDB_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQLDB_HOST'] %>
